# Generated by Django 4.2 on 2025-06-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_payment_client'),
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
