# Generated by Django 4.2 on 2025-06-27 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='INV-', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('format', models.CharField(choices=[('sequential', 'Sequential Numbering'), ('year', 'Year-based Numbering'), ('month', 'Month-based Numbering')], default='sequential', max_length=20)),
                ('payment_terms', models.PositiveSmallIntegerField(default=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('auto_increment', models.BooleanField(default=True)),
                ('tax_included', models.BooleanField(default=False)),
                ('auto_reminders', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice Settings',
            },
        ),
    ]
