# Generated by Django 4.2 on 2025-06-28 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesettings',
            name='auto_increment',
        ),
        migrations.RemoveField(
            model_name='invoicesettings',
            name='format',
        ),
        migrations.RemoveField(
            model_name='invoicesettings',
            name='next_number',
        ),
        migrations.RemoveField(
            model_name='invoicesettings',
            name='prefix',
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NumberingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Services', 'Products')", max_length=100)),
                ('prefix', models.CharField(default='INV-', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('format', models.CharField(choices=[('sequential', 'Sequential Numbering'), ('year', 'Year-based Numbering'), ('month', 'Month-based Numbering'), ('custom', 'Custom Format')], default='sequential', max_length=20)),
                ('custom_format', models.CharField(blank=True, help_text="Use placeholders: {year}, {month}, {day}, {seq}. Example: 'INV-{year}-{seq:05d}'", max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbering_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
