# Generated by Django 4.2 on 2025-06-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_user'),
        ('invoice', '0004_alter_payment_client_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(default=django.db.models.deletion.DO_NOTHING, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payments', to='partners.partner'),
        ),
    ]
