# Generated by Django 4.2 on 2025-06-27 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_user'),
        ('invoice', '0006_alter_payment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='partners.partner'),
        ),
    ]
